### PR TITLE
Fix issue #2, adds basis for localization via i18n_subsites

### PR DESCRIPTION
**Pull request by schalkneethling**
Adds i18n_subsites and needed config for template localization, babel, i18n_subsites and existing pages.

### CODE REVIEW

**Comment by ror6ax** [comment]
Thanks for PR. Import seems to be failing, but almost there!

**Comment by schalkneethling** [comment]
> Thanks for PR. Import seems to be failing, but almost there!

Seems like it the `makefile` that is causing the problem. It somehow does not add the plugins? I will take a look.

**Comment by schalkneethling** [comment]
Interestingly, when I run `make html` locally, it works without any problems. Wonder, do you want to kick that build of again, and specify that it should run without cache?

**Comment by schalkneethling** [comment]
@ror6ax Have you tried to re-run the Travis build without cache?

**Comment by ror6ax** [comment]
git submodules are weird ;)
Reuploading worker as a charm.

Just in case you would be insterested http://asu.kpi.ua/ has an english version. Adding those pages here would be greatly appreciated!

**Comment by schalkneethling** [comment]
@ror6ax  ~ I wonder if the pull request needs to hacktoberfest label?

**Comment by ror6ax** [comment]
No, I don't think so. In fact, the rules say that any PR is eligible, even those without any issues whatsoever.
Labels are just a way to attract people's attention to your project.

**Pull request merged**
